Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TopAutos.Context;
using TopAutos.Models;
using Microsoft.AspNetCore.Http;

namespace TopAutos.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly TopAutosDatabaseContext _context;

        public UsuarioController(TopAutosDatabaseContext context)
        {
            _context = context;
        }

        public IActionResult Login()
        {
            return View();
        }

        // GET: Usuario/Create
        public IActionResult Create()
        {
            return View();
        }


        // GET: Usuario/Fallo
        
        public IActionResult Fallo()
        {
            return View("~/Views/Usuario/Fallo.cshtml");
        }

        // POST: Usuario/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Nombre,Email,Clave,Rol")] Usuario usuario)
        {

            if (ModelState.IsValid)
            {
                _context.Add(usuario);
                await _context.SaveChangesAsync();
                HttpContext.Session.SetString("userName", usuario.Nombre);
                HttpContext.Session.SetInt32("userId", usuario.Id);
                HttpContext.Session.SetInt32("userRole", usuario.Rol);
                return Redirect("/");
            }
            return View(usuario);
        }

        // POST: Usuario/Create
        [HttpPost]
        public async Task<IActionResult> Login(String Email, String Clave)
        {
            
            var usuario = await _context.Usuarios.FirstOrDefaultAsync(m => m.Email == Email && m.Clave == Clave);

            if (usuario == null)
            {

               
                return Redirect("/Usuario/Fallo");

            }

            HttpContext.Session.SetString("userName", usuario.Nombre);
            HttpContext.Session.SetInt32("userId", usuario.Id);
            HttpContext.Session.SetInt32("userRole", usuario.Rol);

            return Redirect("/");
            
            
        }



        // POST: Usuario/Logout
        public async Task<IActionResult> Logout()
        {
            HttpContext.Session.Clear();
            return Redirect("/");
        }

    }
}

Controllers/VehiculosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TopAutos.Context;
using TopAutos.Models;

namespace TopAutos.Controllers
{
    public class VehiculosController : Controller
    {
        private readonly TopAutosDatabaseContext _context;
        private int LoggedId;
        private int LoggedRole;
        public VehiculosController(TopAutosDatabaseContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;

            if (httpContextAccessor.HttpContext.Session.GetInt32("userId") != null)
            {
                LoggedId = (int)httpContextAccessor.HttpContext.Session.GetInt32("userId");
            }
            if (httpContextAccessor.HttpContext.Session.GetInt32("userRole") != null)
            {
                LoggedRole = (int)httpContextAccessor.HttpContext.Session.GetInt32("userRole");
            }
        }

        // GET: Vehiculos
        public async Task<IActionResult> Index()
        {
            if (LoggedRole != 1)
            {
                return Redirect("/");
            }
            
            return View(await _context.Vehiculos.ToListAsync());
        }

        // GET: Vehiculos/Calificador
        public async Task<IActionResult> Calificador()
        {
            if (LoggedId == 0)
            {
                return Redirect("/Usuario/Login");
            }
            return View(await _context.Vehiculos.ToListAsync());
        }

        // GET: Vehiculos/Ranking
        public async Task<IActionResult> Ranking()
        {
            var vehiculos = await _context.Vehiculos.Where(v => v.Voto > 0).OrderByDescending(v => v.Voto).ToListAsync(); 

            return View(vehiculos);
        }


        // GET: Vehiculos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehiculo = await _context.Vehiculos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vehiculo == null)
            {
                return NotFound();
            }

            return View(vehiculo);
        }

        // GET: Vehiculos/InfoVehiculo/5
        public async Task<IActionResult> InfoVehiculo(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehiculo = await _context.Vehiculos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vehiculo == null)
            {
                return NotFound();
            }

            return View(vehiculo);
        }

        // GET: Vehiculos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Vehiculos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Modelo,Marca,Ano,CantPuertas,Precio,VieneAutomatico,Tipo,Voto,Imagen")] Vehiculo vehiculo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(vehiculo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(vehiculo);
        }

        // GET: Vehiculos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehiculo = await _context.Vehiculos.FindAsync(id);
            if (vehiculo == null)
            {
                return NotFound();
            }
            return View(vehiculo);
        }

        // POST: Vehiculos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Modelo,Marca,Ano,CantPuertas,Precio,VieneAutomatico,Tipo,Voto,Imagen")] Vehiculo vehiculo)
        {
            if (id != vehiculo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vehiculo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VehiculoExists(vehiculo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(vehiculo);
        }

        // GET: Vehiculos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehiculo = await _context.Vehiculos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vehiculo == null)
            {
                return NotFound();
            }

            return View(vehiculo);
        }

        // POST: Vehiculos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var vehiculo = await _context.Vehiculos.FindAsync(id);
            _context.Vehiculos.Remove(vehiculo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VehiculoExists(int id)
        {
            return _context.Vehiculos.Any(e => e.Id == id);
        }

        
        // GET: Vehiculos/Buscador/
        public async Task<IActionResult> Buscador(String modelo, String marca, int ano, int tipo)
        {
            if (LoggedId == 0)
            {
                return Redirect("/Usuario/Login");
            }

            // De esta forma voy acumulando los parametros en la query
            IQueryable<Vehiculo> query = _context.Vehiculos;

            //Para que cuando nadie busca nada, me muestre todo el listado
            if (modelo == null && marca == null && ano == 0) 
            {
                query = _context.Vehiculos;
            }

            if (modelo != null)
            {
                query = query.Where(p => p.Modelo.Contains(modelo));
            }

            if (marca != null)
            {
                query = query.Where(p => p.Marca.Contains(marca));
            }

            if (ano != 0)
            {
                query = query.Where(p => p.Ano == ano);
            }

            //if (tipoVehiculo != 0){
            Console.WriteLine(tipo);
            switch (tipo)
            {
                case 1:
                    query = query.Where(p => p.Tipo == TipoVehiculo.Auto);
                    break;
                case 2:
                    query = query.Where(p => p.Tipo == TipoVehiculo.PickUp);
                    break;
                case 3:
                    query = query.Where(p => p.Tipo == TipoVehiculo.SUV);
                    break;
                case 4:
                    query = query.Where(p => p.Tipo == TipoVehiculo.Deportivo);
                    break;
            }
            //}

            //Contenido de la query en una lista: 
            List<Vehiculo> vehiculos = query.ToList();

            return View(vehiculos);
        }

        //GET: Vehiculos/VehiculosFav
        public async Task<IActionResult> VehiculosFav()
        {
            if (LoggedId == 0)
            {
                return Redirect("/Usuario/Login");
            }

            var usuario = await _context.Usuarios.FirstOrDefaultAsync(m => m.Id == LoggedId);
            if (usuario == null)
            {
                return StatusCode(400);
            }

            // En la vista de vehiculos favs se van a guardar los vehiculos que el usuario califico con cuatro o mas.
            var vehiculosUsuario = _context.VotosUsuario.Where(u => u.Usuario == usuario && u.Voto >= 4)
                .Select(v => v.Vehiculo).OrderByDescending(v => v.Voto).ToList();



            

            return View(vehiculosUsuario);
        }

        // POST: Vehiculos/Calificacion
        [HttpPost]
        public async Task<IActionResult> Calificacion(int vehiculoId, int voto)
        {
            //Despues evaluar si esta logueado
            if (LoggedId == 0)
            {
                return Redirect("/Usuario/Login");
            }

            Console.WriteLine("VEHICULO QUE CALIFICA - ID: " + vehiculoId);
            Console.WriteLine("VOTO QUE PUSO: " + voto);

            var usuario = await _context.Usuarios.FirstOrDefaultAsync(m => m.Id == LoggedId); // Evaluar si tengo varios, con if al principio
            var vehiculo = await _context.Vehiculos.FirstOrDefaultAsync(m => m.Id == vehiculoId);
            var votosUsuario = await _context.VotosUsuario.FirstOrDefaultAsync(m => m.Usuario == usuario && m.Vehiculo == vehiculo);

            if (votosUsuario != null)
            {
                votosUsuario.Voto = voto;
                _context.VotosUsuario.Update(votosUsuario);
            }
            else
            {
                VotosUsuario votoUsuario = new VotosUsuario { Usuario = usuario, Vehiculo = vehiculo, Voto = voto };
                _context.VotosUsuario.Add(votoUsuario);
            }

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

@{ var _session = HttpContextAccessor.HttpContext.Session;}

@{ String userName = _session.GetString("userName"); }

@{int userRole = 0;}

@if (_session.GetInt32("userRole") != null)
{
    userRole = (int)_session.GetInt32("userRole");
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TopVehiculos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img width="40" src="~/img/TopSinTexto.png" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse">
                    <ul class="navbar-nav flex-grow-1">
                        @if (userRole == 1)
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vehiculos" asp-action="Index">Vehiculos</a>
                        </li>}
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vehiculos" asp-action="Ranking">Ranking</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vehiculos" asp-action="Calificador">Califica</a>
                        </li>
                        @if (userName != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Vehiculos" asp-action="Buscador">Buscador</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Vehiculos" asp-action="VehiculosFav">Mis vehiculos</a>
                            </li>
}
                    </ul>

                    @if (userName != null)
                    {
                        <div class="usuario">
                            @userName
                        </div>

                        <div class="salir" text-right>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Logout">Salir</a>
                        </div> }
                    else
                    {
                        <div class="ingresar" text-right>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Login">Iniciar sesion</a>
                        </div>

                        <div class="registrar" text-right>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Create">Registrarme</a>
                        </div>}


                </div>

            </div>
        </nav>

        
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    @RenderSection("Scripts", required: false)
    <script src="~/lib/jquery/dist/jquery.min.js"></script> <!--libreria para el onclick-->
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> <!--boostrap de js  <script src="~/js/site.js"></script>  -->
    <script src="~/js/site.js" asp-append-version="true"></script>

</body>
</html>